project:
  type: website
  output-dir: docs           # <-- /docs mode
  resources:
    - CNAME                  # ensure it gets copied into /docs

website:
  title: "Home"
  site-url: https://ransiclark.com   # <-- your domain (use https)
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  navbar:
    background: light
    title: Ransi Clark

      


format:
  html:
    max-width: 100px
    fontsize: 15px
    theme: [cosmo, styles.scss]

