project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  navbar:
    background: light
    title: Ransi Clark
    right:
      - text: Papers
        href: papers.qmd

format:
  html:
    max-width: 100px
    fontsize: 15px
    theme: [cosmo, styles.scss]

